# THIS IS A GENERATED FILE, DO NOT EDIT. GENERATED BY https://github.com/onmetal-dev/metal/actions/workflows/release.yml
class Cli < Formula
  desc "The missing PaaS for Hetzner"
  homepage "https://github.com/onmetal-dev/metal"
  version "v0.0.1-alpha-9_15"
  base_url = "https://github.com/onmetal-dev/metal/releases/download/#{version}"

  # Each release of the Metal CLI contains binaries for MacOS, Linux etc compressed into
  # separate .tar.gz files. So no building of source code is necessary. We only need
  # to download, verify and install those binaries. That's why we use bin.install.
  # For more info on that method, see:
  # https://docs.brew.sh/Formula-Cookbook#bininstall-foo

  on_macos do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-darwin-arm64.tar.gz"
      sha256 "26c65a6414f6e27944aa054061b163e8b0d1f9c526072d643ee7ebab2eb5c2f9"

      def install
        bin.install "metal-#{version}-darwin-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-darwin-x64.tar.gz"
      sha256 "4e5e3e6e0f0b444e34a2ec38514c6780932a6d383cacbb0c81f668af179766df"


      def install
        bin.install "metal-#{version}-darwin-x64" => "metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-linux-arm64.tar.gz"
      sha256 "531e596dbeddef2fe74513b747bb3c5fb37d59b62507fa223ae0fc5a829b668d"

      def install
        bin.install "metal-#{version}-linux-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-linux-x64.tar.gz"
      sha256 "26d5ad2b269db4b60c3546c1abc1cac1f470415e54271841532fc14fa5a2e4bd"

      def install
        bin.install "metal-#{version}-linux-x64" => "metal"
      end
    end
  end
