# THIS IS A GENERATED FILE, DO NOT EDIT. GENERATED BY https://github.com/onmetal-dev/metal/actions/workflows/release.yml
class Cli < Formula
  desc "The missing PaaS for Hetzner"
  homepage "https://github.com/onmetal-dev/metal"
  version "v0.0.1-alpha-9_17"
  base_url = "https://github.com/onmetal-dev/metal/releases/download/#{version}"

  # Each release of the Metal CLI contains binaries for MacOS, Linux etc compressed into
  # separate .tar.gz files. So no building of source code is necessary. We only need
  # to download, verify and install those binaries. That's why we use bin.install.
  # For more info on that method, see:
  # https://docs.brew.sh/Formula-Cookbook#bininstall-foo

  on_macos do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-darwin-arm64.tar.gz"
      sha256 "4261d8bdcbd737459f4dee5ce5886291bfee92863445acbf8d48b543454a7854"

      def install
        bin.install "metal-#{version}-darwin-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-darwin-x64.tar.gz"
      sha256 "238279b4286bd3503244a2bf0fd33f2f51ba14bea0057e2ec66dc90d9834beb1"


      def install
        bin.install "metal-#{version}-darwin-x64" => "metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-linux-arm64.tar.gz"
      sha256 "e57422df9a3e3f5da5d6cb0cff4c783a33e86c7df36125f8904efcbdb21b1946"

      def install
        bin.install "metal-#{version}-linux-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-linux-x64.tar.gz"
      sha256 "b5db0b5d7fb06eecff9054134184deee489513297a0af11e8b0b9b538ccb7347"

      def install
        bin.install "metal-#{version}-linux-x64" => "metal"
      end
    end
  end

  test do
    system "#{bin}/metal", "--version"
    system "metal", "--version"
  end
end
