# THIS IS A GENERATED FILE, DO NOT EDIT. GENERATED BY https://github.com/onmetal-dev/metal/actions/workflows/release.yml
class CliAT001Alpha918 < Formula
  desc "The missing PaaS for Hetzner"
  homepage "https://github.com/onmetal-dev/metal"
  version "v0.0.1-alpha-9_18"
  base_url = "https://github.com/onmetal-dev/metal/releases/download/#{version}"

  # Each release of the Metal CLI contains binaries for MacOS, Linux etc compressed into
  # separate .tar.gz files. So no building of source code is necessary. We only need
  # to download, verify and install those binaries. That's why we use bin.install.
  # For more info on that method, see:
  # https://docs.brew.sh/Formula-Cookbook#bininstall-foo

  on_macos do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-darwin-arm64.tar.gz"
      sha256 "147f8d1cab7f008fd775920d81f09d45df01a0fbf80f51b31e27c3e163b76c04"

      def install
        bin.install "metal-#{version}-darwin-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-darwin-x64.tar.gz"
      sha256 "23156280fbea5e9d4abdb9db048b2ff1579252ea190ce38e0d2c9fbde14af701"


      def install
        bin.install "metal-#{version}-darwin-x64" => "metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-linux-arm64.tar.gz"
      sha256 "782342e0af188ea15f64b8ea6340e2d7b7c37bab72f89590c41e9d1042c941d0"

      def install
        bin.install "metal-#{version}-linux-arm64" => "metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-linux-x64.tar.gz"
      sha256 "c06a7959b06ad946435936451164b82fda594fc0ec7de15d9f7efe2b2f80794a"

      def install
        bin.install "metal-#{version}-linux-x64" => "metal"
      end
    end
  end

  test do
    system "#{bin}/metal", "--version"
    system "metal", "--version"
  end
end
