# THIS IS A GENERATED FILE, DO NOT EDIT. GENERATED BY https://github.com/onmetal-dev/metal/actions/workflows/release.yml
class CliAT001Alpha919 < Formula
  desc "The missing PaaS for Hetzner"
  homepage "https://github.com/onmetal-dev/metal"
  version "v0.0.1-alpha-9_19"
  base_url = "https://github.com/onmetal-dev/metal/releases/download/#{version}"

  # Each release of the Metal CLI contains binaries for MacOS, Linux etc compressed into
  # separate .tar.gz files. So no building of source code is necessary. We only need
  # to download, verify and install those binaries. That's why we use bin.install.
  # For more info on that method, see:
  # https://docs.brew.sh/Formula-Cookbook#bininstall-foo

  on_macos do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-darwin-arm64.tar.gz"
      sha256 "2873b893b393bc19c80f5369f40f250ef671972166d3e05befaf8bbc53532b92"

      def install
        command_name = "metal-#{version}-darwin-arm64"
        bin.install command_name
        # Inspired by: https://github.com/argoproj/homebrew-tap/blob/e8b04ee8b260b5675cd646d8acbbe3e32a9924f5/kubectl-argo-rollouts%401.2.rb#L21
        mv bin/ + command_name.to_s, bin/"metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-darwin-x64.tar.gz"
      sha256 "bd0c7e6c2d2d482b947be62195a808f6d2604396ca45b58ed6596385548d1471"


      def install
        command_name = "metal-#{version}-darwin-x64"
        bin.install "metal-#{version}-darwin-x64"
        mv bin/ + command_name.to_s, bin/"metal"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm?
      url "#{base_url}/metal-#{version}-linux-arm64.tar.gz"
      sha256 "e0dc366105a8e2d3ae610a87b822a03f3c68d662f545f450a0551a940254aa70"

      def install
        command_name = "metal-#{version}-linux-arm64"
        bin.install "metal-#{version}-linux-arm64"
        mv bin/ + command_name.to_s, bin/"metal"
      end
    end

    if Hardware::CPU.intel?
      url "#{base_url}/metal-#{version}-linux-x64.tar.gz"
      sha256 "61fe0ffa77e6a6fa41c624660289b8a19164c34cfb875bb43634b39034a378d1"

      def install
        command_name = "metal-#{version}-linux-x64"
        bin.install "metal-#{version}-linux-x64"
        mv bin/ + command_name.to_s, bin/"metal"
      end
    end
  end

  test do
    system "#{bin}/metal", "--version"
    system "metal", "--version"
  end
end
